 
# Node.js
# Build a general Node.js project with npm.
# Add steps that analyze code, save build artifacts, deploy, and more:
# https://docs.microsoft.com/azure/devops/pipelines/languages/javascript

trigger:
- master

pool:
  vmImage: 'ubuntu-latest'

steps:
- task: oc-setup@2
  inputs:
    connectionType: 'OpenShift Connection Service'
    openshiftService: 'OCP'
- task: oc-cmd@2
  inputs:
    connectionType: 'OpenShift Connection Service'
    openshiftService: 'OCP'
    cmd: 'oc new-project demo'
    ignoreFlag: true
- task: oc-cmd@2
  inputs:
    connectionType: 'OpenShift Connection Service'
    openshiftService: 'OCP'
    cmd: 'oc new-app https://github.com/caetanomedeiros/nodejs-ex.git -l name=demoapp -n demo'
    ignoreFlag: true
- task: oc-cmd@2
  inputs:
    connectionType: 'OpenShift Connection Service'
    openshiftService: 'OCP'
    cmd: 'oc start-build nodejs-ex --follow -n demo'
- task: oc-cmd@2
  inputs:
    connectionType: 'OpenShift Connection Service'
    openshiftService: 'OCP'
    cmd: 'oc expose service/nodejs-ex -n demo'
    ignoreFlag: true
- task: oc-cmd@2
  inputs:
    connectionType: 'OpenShift Connection Service'
    openshiftService: 'OCP'
    cmd: 'oc status -n demo'